import streamlit as st
from pathlib import Path
import json
st.set_page_config(layout="wide")
st.title("📊 Scraping")

file_path = Path("data/raw/trustpilot_reviews_production.json")

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

#st.write(data)

import pandas as pd

df = pd.DataFrame(data)
st.subheader("Raw data after basic cleaning")
st.markdown("""
This section provides a first overview of the dataset and describes how we scraped the data and did basic cleaning. 
The data was scraped from different domains of the Trustpilot platform. 

""")
st.dataframe(df.head(20))

st.subheader("Data collection and rights")
st.markdown("""
The data used in this project consists of customer reviews collected from the Trustpilot platform. While these reviews are publicly accessible, they are not freely available for unrestricted reuse. Access to the data is governed by Trustpilot’s terms of service.

The reviews are generated by users of the platform, but the Trustpilot company owns and controls the distribution and use of this data. Therefore, any reuse must comply with their legal and ethical guidelines.

The dataset was obtained through web scraping of publicly available reviews. This process was conducted solely for academic purposes. Care was taken to respect ethical considerations, including:
Collecting only publicly accessible data
Avoiding personal or sensitive information
Using the data exclusively for non-commercial, educational purposes

It is important to note that web scraping may be subject to legal restrictions depending on the platform’s policies. This project does not intend to redistribute the data and uses it strictly within an academic context.
""")

st.subheader("Technical Problems and challenges with Scraping")
st.markdown("""
Problems with scraping include dynamical contents and detection bots. This meant that we had to adapt the scraper for different data. It also meant that 
the different data sources had to be brought together. Trustpilot partly loads overlapping contents while scrolling. 
Since there was no ID those duplicates where unavoidable. There is also a limit to how many pages of reviews one can see. 
Therefore the data is not complete.
Summary:
Problem with scraping
solution
Dynamical content
Adapt scraping script each time
Detection bots
Use different trustpilot platforms
Different data sources
Standardize the data
Duplicates ,overlapping contents
Search and delete them in cleaning process
Data incompleteness
Unavoidable, not solvable
""")
df = pd.DataFrame({
    "Problem with scraping": [
        "Dynamical content",
        "detection bots",
        "different data sources",
        "duplicates,overlapping contents",
        "data incompleteness"
    ],
    "Solution": [
        "adapt scraping script each time",
        "use differnt domains of trustpilot platforms",
        "Standardize the data",
        "search and delete them in cleaning process",
        "unavoidable, not solvable"
    ]
})

st.table(df)